### ISSUE TITLE
006 - Implementar a geração de lotes

### ISSUE THREAD

**Issue by kauanrossii** [GH-eduardo/Magic-the-Gathering#18]
Eu, como sistema, preciso realizar a análise do baralho de maneira rápida e paralelizada, desse modo, visa-se necessário separar o baralho em lotes contendo um conjunto das cartas a serem analisadas, pois os demais serviços precisam dessa informação para prosseguir no processamento de maneira consistente.

O projeto api deverá, após concluir com sucesso a validação inicial, e a inserção das entidades importação e status no banco de dados, realizar a geração de lotes do baralho, sendo que cada um deles deverá conter um conjunto de 20 cartas a serem analisadas unitariamente por outro serviço (como dentro das 100 cartas do baralho uma delas é o commander, um dos lotes irá conter apenas 19 cartas a serem analisadas).
* É necessário que seja validado que os lotes não repitam as cartas, ou seja, se um lote é da carta 1 a 20, o próximo lote não pode conter a carta 20 para que não tenham falsas validações por outro serviço. 
* Cada um dos lotes deverão ser registrados no banco de dados, contendo o conteúdo das cartas em formato json e salvo em uma coluna bjson padrão do postgresql para esse tipo de armazenamento.
* Cada um dos lotes deverá conter, também, uma lista de status para indicar o andamento do seu processamento, sendo que o primeiro é "Criado". O status deverá armazenar também a data que ele foi gerado (status) e um campo de observação caso seja necessário informar um erro.

**Comment by GH-eduardo** [comment]
só pode haver cartas repetidas se for um 'terreno básico' ou estiver explícito que pode repetir no texto da carta
