### ISSUE TITLE
013 - Implementar a análise das cartas do lote

### ISSUE THREAD

**Issue by kauanrossii** [GH-eduardo/Magic-the-Gathering#26]
Eu, como sistema, preciso que seja verificado, de maneira unitária, a validade de cada uma das cartas do lote da importação, pois preciso ter o controle fino dos baralhos que estão sendo importados no sistema.

* Para cada uma das cartas especificadas no lote, deverá ser validado se:
	* A cor da carta condiz com as cores do commander do baralho;
	* A carta existe na api do magic;
	* O baralho não contém essa carta (a carta só poderá ser duplicada se for do tipo basic land).
* Para cada uma das cartas, deverá ser criado um registro no banco de dados da entidade "Importação carta", que deve conter as informações da carta do baralho, ou seja, o id, e o resultado da importação (se condiz com as condições do tópico acima ou não). Caso a carta falhe em alguma das validações, deverá ser expresso no campo "observação" da entidade, o motivo de ter falhado.

**Comment by B0nam** [comment]
Trabalho entregue.
